teachers :
  - llama
  - t5

root : 'datasets'

datasets :
  obqa:
    filepath: 'datasets/obqa'

  arc:
    filepath: 'datasets/arc'

  piqa:
    filepath: 'datasets/piqa'

  riddle:
    filepath: 'datasets/riddle'

  pubmedqa:
    filepath: 'datasets/pubmedqa'

  bioasq:
    filepath: 'datasets/bioasq'
